In [2]:
import numpy as np

In [3]:
a= np.random.randint(1,100,24).reshape(6,4)
b= np.random.randint(1,100,10)


In [4]:
np.sort(b)[::-1] # descending for 1D array

array([82, 78, 71, 65, 50, 38, 34, 33, 27,  6], dtype=int32)

In [5]:
np.sort(a,axis=0 )

array([[18,  4,  1,  7],
       [21, 48, 30, 40],
       [22, 68, 42, 59],
       [38, 70, 63, 67],
       [45, 78, 76, 72],
       [54, 93, 90, 86]], dtype=int32)

In [6]:
np.sort(b)

array([ 6, 27, 33, 34, 38, 50, 65, 71, 78, 82], dtype=int32)

In [7]:
np.append(a,300)

array([ 38,  70,   1,  67,  22,  93,  63,  59,  54,   4,  76,  72,  18,
        78,  90,   7,  45,  48,  30,  40,  21,  68,  42,  86, 300])

In [8]:
np.append(a,np.ones((a.shape[0],1)),axis=1) # to append a column of ones

array([[38., 70.,  1., 67.,  1.],
       [22., 93., 63., 59.,  1.],
       [54.,  4., 76., 72.,  1.],
       [18., 78., 90.,  7.,  1.],
       [45., 48., 30., 40.,  1.],
       [21., 68., 42., 86.,  1.]])

In [9]:
# CONCATENATE

c= np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=0) # rowwise for replacement of hstack and vstack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1) # columnwise for replacement of hstack and vstack

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [13]:
# np.unique()

a= np.array([1,1,1,2,2,2,3,3,3,])

In [14]:
np.unique(a)

array([1, 2, 3])

In [15]:
# np.expand_dims()

np.expand_dims(a,axis=0) # make row and column vector



array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [16]:
# np.where()

np.where(a<3)


(array([0, 1, 2, 3, 4, 5]),)

In [17]:
np.where(a<3,0,a) # if condition true replace with 0 , else a.


array([0, 0, 0, 0, 0, 0, 3, 3, 3])

In [18]:
# np.argmax()

np.argmax(a)

np.int64(6)

In [19]:
np.argmax(c,axis=0)

array([1, 1, 1])

In [20]:
np.argmin(c)

np.int64(0)

In [21]:
# np.cumsum() (cumilitive sum)

np.cumsum(a) # 1+1+1+2+2+2+3+3+3 , without axis it will return in 1D

array([ 1,  2,  3,  5,  7,  9, 12, 15, 18])

In [22]:
np.cumsum(d,axis=0)

array([[ 6,  7,  8],
       [15, 17, 19]])

In [23]:
np.cumprod(a)

array([  1,   1,   1,   2,   4,   8,  24,  72, 216])

In [25]:
a 

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [26]:
np.percentile(a,100)

np.float64(3.0)

In [27]:
np.percentile(a,0)

np.float64(1.0)

In [28]:
np.percentile(a,50)

np.float64(2.0)

In [30]:
# np. histogram()

np.histogram(a,bins=[0,10,20,30])

(array([9, 0, 0]), array([ 0, 10, 20, 30]))

In [35]:
# np.corrcoef(): corelation -1 to 1.

salary = np.array([3000,4000,5000,3500])
experience =np.array([1,2,3,5])
np.corrcoef(salary,experience)

array([[1. , 0.2],
       [0.2, 1. ]])

In [39]:
# np.isin(): help to check multiple items are present in array or not.

np.isin(a,b)

array([False, False, False, False, False, False, False, False, False])

In [40]:
# np.flip()

np.flip(a)

array([3, 3, 3, 2, 2, 2, 1, 1, 1])

In [ ]:
np.flip(c,axis=1) # 2D

array([[2, 1, 0],
       [5, 4, 3]])

In [48]:
# np.put()

np.put(a,[0,1],[333,1333])

In [49]:
a

array([ 333, 1333,    1,    2,    2,    2,    3,    3,    3])

In [50]:
#np.delete()

np.delete(a,4)

array([ 333, 1333,    1,    2,    2,    3,    3,    3])

In [62]:
np.append(a,[4])

array([ 333, 1333,    1,    2,    2,    2,    3,    3,    3,    4])

In [69]:
e=np.delete(b,[9])

In [64]:
np.size(a)

9

In [70]:
np.size(e)

9

In [71]:
np.union1d(a,e)

array([   1,    2,    3,    6,   33,   34,   38,   50,   65,   71,   78,
         82,  333, 1333])

In [72]:
np.intersect1d(a,e)

array([], dtype=int64)

In [73]:
np.setdiff1d(a,e)

array([   1,    2,    3,  333, 1333])

In [74]:
np.setdiff1d(a,e)

array([   1,    2,    3,  333, 1333])

In [75]:
np.setxor1d(a,e)

array([   1,    2,    3,    6,   33,   34,   38,   50,   65,   71,   78,
         82,  333, 1333])

In [ ]:
np.isin(a,e) # np.in1d()

array([False, False, False, False, False, False, False, False, False])

In [ ]:
# np.clip() cuts a clip from array
np.clip(a,a_max=71,a_min=3)

array([71, 71,  3,  3,  3,  3,  3,  3,  3])